package api

var ERROR_CODE_HASH_PASS_FAILED = "ERR-HP001"
var ERROR_CODE_WRONG_CREDENTIALS = "ERR-WP041"
var ERROR_DUPLICATED_STATUS = "ERR-DS041"
var ERROR_ENVIRONMENT_VARIABLES = "ERR-ENV001"
var ERROR_DATABASE_CONNECTION = "ERR-DB001"
