// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
  "schemes": ["http"],
  "swagger": "2.0",
  "info": {
    "description": "A comprehensive REST API for managing tasks, workflows, and task management",
    "title": "TODO API",
    "contact": {
      "name": "API Support"
    },
    "license": {
      "name": "MIT"
    },
    "version": "1.0.0"
  },
  "host": "localhost:8080",
  "basePath": "/api/v1",
  "paths": {
    "/health": {
      "get": {
        "description": "Check the health status of the API and database connection",
        "tags": ["Health"],
        "summary": "Health check",
        "operationId": "healthCheck",
        "responses": {
          "200": {
            "description": "Application is healthy",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/todo": {
      "get": {
        "description": "Retrieve a list of all tasks",
        "tags": ["Tasks"],
        "summary": "Get all tasks",
        "operationId": "getAllTasks",
        "parameters": [
          {
            "type": "integer",
            "default": 10,
            "description": "Maximum number of tasks to return",
            "name": "limit",
            "in": "query"
          },
          {
            "type": "integer",
            "default": 0,
            "description": "Number of tasks to skip",
            "name": "offset",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List of tasks",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Task"
              }
            }
          }
        }
      },
      "post": {
        "description": "Create a new task with title, description, author, and deadline",
        "consumes": ["application/json"],
        "tags": ["Tasks"],
        "summary": "Create a new task",
        "operationId": "createTask",
        "parameters": [
          {
            "description": "Create task request",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateTaskRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Task created successfully",
            "schema": {
              "$ref": "#/definitions/Task"
            }
          }
        }
      }
    },
    "/todo/{id}": {
      "get": {
        "description": "Retrieve a single task by its ID",
        "tags": ["Tasks"],
        "summary": "Get a specific task",
        "operationId": "getTask",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "Task ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Task details",
            "schema": {
              "$ref": "#/definitions/Task"
            }
          }
        }
      },
      "put": {
        "description": "Update an existing task",
        "consumes": ["application/json"],
        "tags": ["Tasks"],
        "summary": "Update a task",
        "operationId": "updateTask",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "Task ID",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "Update task request",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateTaskRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Task updated successfully",
            "schema": {
              "$ref": "#/definitions/Task"
            }
          }
        }
      },
      "delete": {
        "description": "Delete a task by its ID",
        "tags": ["Tasks"],
        "summary": "Delete a task",
        "operationId": "deleteTask",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "Task ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "Task deleted successfully"
          }
        }
      }
    },
    "/todo/author/{userID}": {
      "get": {
        "description": "Retrieve all tasks created by a specific user",
        "tags": ["Tasks"],
        "summary": "Get tasks by author",
        "operationId": "getTasksByAuthor",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "User ID",
            "name": "userID",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "List of tasks",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Task"
              }
            }
          }
        }
      }
    },
    "/todo/overdue": {
      "get": {
        "description": "Retrieve all tasks that are overdue and not completed",
        "tags": ["Tasks"],
        "summary": "Get overdue tasks",
        "operationId": "getOverdueTasks",
        "responses": {
          "200": {
            "description": "List of overdue tasks",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Task"
              }
            }
          }
        }
      }
    },
    "/todo/responsible/{userID}": {
      "get": {
        "description": "Retrieve all tasks assigned to a specific user",
        "tags": ["Tasks"],
        "summary": "Get tasks by responsible user",
        "operationId": "getTasksByResponsible",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "User ID",
            "name": "userID",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "List of tasks",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Task"
              }
            }
          }
        }
      }
    },
    "/statuses": {
      "get": {
        "description": "Retrieve a list of all task statuses",
        "tags": ["Task Status"],
        "summary": "Get all task statuses",
        "operationId": "getAllTaskStatuses",
        "responses": {
          "200": {
            "description": "List of task statuses",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/TaskStatus"
              }
            }
          }
        }
      },
      "post": {
        "description": "Create a new task status",
        "consumes": ["application/json"],
        "tags": ["Task Status"],
        "summary": "Create a new task status",
        "operationId": "createTaskStatus",
        "parameters": [
          {
            "description": "Create task status request",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateTaskStatusRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Task status created successfully",
            "schema": {
              "$ref": "#/definitions/TaskStatus"
            }
          }
        }
      }
    },
    "/statuses/{id}": {
      "get": {
        "description": "Retrieve a single task status by its ID",
        "tags": ["Task Status"],
        "summary": "Get a specific task status",
        "operationId": "getTaskStatus",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "Task Status ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Task status details",
            "schema": {
              "$ref": "#/definitions/TaskStatus"
            }
          }
        }
      },
      "put": {
        "description": "Update an existing task status",
        "consumes": ["application/json"],
        "tags": ["Task Status"],
        "summary": "Update a task status",
        "operationId": "updateTaskStatus",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "Task Status ID",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "Update task status request",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateTaskStatusRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Task status updated successfully",
            "schema": {
              "$ref": "#/definitions/TaskStatus"
            }
          }
        }
      },
      "delete": {
        "description": "Delete a task status by its ID",
        "tags": ["Task Status"],
        "summary": "Delete a task status",
        "operationId": "deleteTaskStatus",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "Task Status ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "Task status deleted successfully"
          }
        }
      }
    },
    "/task-type": {
      "get": {
        "description": "Retrieve a list of all task types",
        "tags": ["Task Type"],
        "summary": "Get all task types",
        "operationId": "getAllTaskTypes",
        "responses": {
          "200": {
            "description": "List of task types",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/TaskType"
              }
            }
          }
        }
      },
      "post": {
        "description": "Create a new task type",
        "consumes": ["application/json"],
        "tags": ["Task Type"],
        "summary": "Create a new task type",
        "operationId": "createTaskType",
        "parameters": [
          {
            "description": "Create task type request",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateTaskTypeRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Task type created successfully",
            "schema": {
              "$ref": "#/definitions/TaskType"
            }
          }
        }
      }
    },
    "/task-type/{id}": {
      "get": {
        "description": "Retrieve a single task type by its ID",
        "tags": ["Task Type"],
        "summary": "Get a specific task type",
        "operationId": "getTaskType",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "Task Type ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Task type details",
            "schema": {
              "$ref": "#/definitions/TaskType"
            }
          }
        }
      },
      "put": {
        "description": "Update an existing task type",
        "consumes": ["application/json"],
        "tags": ["Task Type"],
        "summary": "Update a task type",
        "operationId": "updateTaskType",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "Task Type ID",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "Update task type request",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateTaskTypeRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Task type updated successfully",
            "schema": {
              "$ref": "#/definitions/TaskType"
            }
          }
        }
      },
      "delete": {
        "description": "Delete a task type by its ID",
        "tags": ["Task Type"],
        "summary": "Delete a task type",
        "operationId": "deleteTaskType",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "Task Type ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "Task type deleted successfully"
          }
        }
      }
    },
    "/workflows": {
      "get": {
        "description": "Retrieve a list of all workflows",
        "tags": ["Workflows"],
        "summary": "Get all workflows",
        "operationId": "getAllWorkflows",
        "responses": {
          "200": {
            "description": "List of workflows",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Workflow"
              }
            }
          }
        }
      },
      "post": {
        "description": "Create a new workflow with statuses",
        "consumes": ["application/json"],
        "tags": ["Workflows"],
        "summary": "Create a new workflow",
        "operationId": "createWorkflow",
        "parameters": [
          {
            "description": "Create workflow request",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateWorkflowRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Workflow created successfully",
            "schema": {
              "$ref": "#/definitions/Workflow"
            }
          }
        }
      }
    },
    "/workflows/{id}": {
      "get": {
        "description": "Retrieve a single workflow by its ID",
        "tags": ["Workflows"],
        "summary": "Get a specific workflow",
        "operationId": "getWorkflow",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "Workflow ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Workflow details",
            "schema": {
              "$ref": "#/definitions/Workflow"
            }
          }
        }
      },
      "put": {
        "description": "Update an existing workflow",
        "consumes": ["application/json"],
        "tags": ["Workflows"],
        "summary": "Update a workflow",
        "operationId": "updateWorkflow",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "Workflow ID",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "Update workflow request",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateWorkflowRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Workflow updated successfully",
            "schema": {
              "$ref": "#/definitions/Workflow"
            }
          }
        }
      },
      "delete": {
        "description": "Delete a workflow by its ID",
        "tags": ["Workflows"],
        "summary": "Delete a workflow",
        "operationId": "deleteWorkflow",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "Workflow ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "Workflow deleted successfully"
          }
        }
      }
    }
  },
  "definitions": {
    "Task": {
      "type": "object",
      "properties": {
        "completed": {
          "type": "boolean"
        },
        "createdAt": {
          "type": "string"
        },
        "deadline": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "status": {
          "$ref": "#/definitions/TaskStatus"
        },
        "title": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/TaskType"
        },
        "updatedAt": {
          "type": "string"
        }
      }
    },
    "CreateTaskRequest": {
      "type": "object",
      "required": ["title", "description", "authorID", "deadline"],
      "properties": {
        "authorID": {
          "type": "integer",
          "format": "int64"
        },
        "deadline": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "UpdateTaskRequest": {
      "type": "object",
      "properties": {
        "completed": {
          "type": "boolean"
        },
        "deadline": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "responsibleID": {
          "type": "integer",
          "format": "int64"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "TaskStatus": {
      "type": "object",
      "properties": {
        "active": {
          "type": "boolean"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "label": {
          "type": "string"
        }
      }
    },
    "CreateTaskStatusRequest": {
      "type": "object",
      "required": ["label", "active"],
      "properties": {
        "active": {
          "type": "boolean"
        },
        "label": {
          "type": "string"
        }
      }
    },
    "UpdateTaskStatusRequest": {
      "type": "object",
      "properties": {
        "active": {
          "type": "boolean"
        },
        "label": {
          "type": "string"
        }
      }
    },
    "TaskType": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "CreateTaskTypeRequest": {
      "type": "object",
      "required": ["name"],
      "properties": {
        "name": {
          "type": "string"
        }
      }
    },
    "UpdateTaskTypeRequest": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      }
    },
    "Workflow": {
      "type": "object",
      "properties": {
        "author": {
          "$ref": "#/definitions/User"
        },
        "createdAt": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "name": {
          "type": "string"
        },
        "statuses": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/TaskStatus"
          }
        }
      }
    },
    "CreateWorkflowRequest": {
      "type": "object",
      "required": ["name", "statuses"],
      "properties": {
        "name": {
          "type": "string"
        },
        "statuses": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/CreateTaskStatusRequest"
          }
        }
      }
    },
    "UpdateWorkflowRequest": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "statuses": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/UpdateTaskStatusRequest"
          }
        }
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "name": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    }
  }
}
`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}{
	Version:     "1.0.0",
	Host:        "localhost:8080",
	BasePath:    "/api/v1",
	Schemes:     []string{"http"},
	Title:       "TODO API",
	Description: "A comprehensive REST API for managing tasks, workflows, and task management",
}

type s struct{}

func (s *s) ReadDoc() string {
	return docTemplate
}

func init() {
	swag.Register(swag.Name, &s{})
}
